import {
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage1,
} from '../assets';

export const benefits = [
  {
    id: '1',
    title: 'Ask anything',
    text: 'Lets users quickly find answers to their questions without having to search through multiple sources.',
    backgroundUrl: 'assets/benefits/card-1.svg',
    iconUrl: benefitIcon1,
    imageUrl: benefitImage1,
  },
  {
    id: '2',
    title: 'Improve everyday',
    text: 'The app uses natural language processing to understand user queries and provide accurate and relevant responses.',
    backgroundUrl: 'assets/benefits/card-2.svg',
    iconUrl: benefitIcon2,
    imageUrl: benefitImage1,
    light: true,
  },
  {
    id: '3',
    title: 'Connect everywhere',
    text: 'Connect with the AI chatbot from anywhere, on any device, making it more accessible and convenient.',
    backgroundUrl: 'assets/benefits/card-3.svg',
    iconUrl: benefitIcon3,
    imageUrl: benefitImage1,
  },
  {
    id: '4',
    title: 'Fast responding',
    text: 'Lets users quickly find answers to their questions without having to search through multiple sources.',
    backgroundUrl: 'assets/benefits/card-4.svg',
    iconUrl: benefitIcon4,
    imageUrl: benefitImage1,
    light: true,
  },
  {
    id: '5',
    title: 'Ask anything',
    text: 'Lets users quickly find answers to their questions without having to search through multiple sources.',
    backgroundUrl: 'assets/benefits/card-5.svg',
    iconUrl: benefitIcon1,
    imageUrl: benefitImage1,
  },
  {
    id: '6',
    title: 'Improve everyday',
    text: 'The app uses natural language processing to understand user queries and provide accurate and relevant responses.',
    backgroundUrl: 'assets/benefits/card-6.svg',
    iconUrl: benefitIcon2,
    imageUrl: benefitImage1,
  },
];
